const data = {
	products: [
		{
			_id: "1",
			name: "Churidar",
			category: "women",
			image: "https://m.media-amazon.com/images/I/71F9sYTKmHS._AC_UL320_.jpg",
			price: 120,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "2",
			name: "Shirt",
			category: "men",
			image: "https://m.media-amazon.com/images/I/71w+tRy3BrL._AC_UL320_.jpg",
			price: 100,
			brand: "Adidas",
			rating: 4.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "3",
			name: "iPhone 15",
			category: "phone",
			image: "https://m.media-amazon.com/images/I/611mRs-imxL._AC_UY218_.jpg",
			price: 220,
			brand: "Lacoste",
			rating: 4.8,
			numReviews: 17,
			description: "high quality product",
		},
		{
			_id: "4",
			name: "Pant",
			category: "pen",
			image: "https://m.media-amazon.com/images/I/712-q5Z3NnL._AC_UL320_.jpg",
			price: 78,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			_id: "5",
			name: "Shoe",
			category: "men",
			image: "https://m.media-amazon.com/images/I/71PZK6gQJcL._AC_UL320_.jpg",
			price: 65,
			brand: "Puma",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "6",
			name: "Dinner set",
			category: "kitchen",
			image: "https://m.media-amazon.com/images/I/71UqeCbFuvL._AC_UL320_.jpg",
			price: 139,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 15,
			description: "high quality product",
		},
	],
};
export default data;
